name: CI

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install tooling
        run: |
          python -m pip install -U pip
          pip install black==24.8.0 ruff==0.6.9 pytest

      # 🧹 รัน ruff แก้อัตโนมัติ "ก่อน"
      - name: Lint (Ruff, autofix)
        run: ruff check . --fix

      # ✅ check ด้วย black "หลัง"
      - name: Lint (Black check)
        run: black --check .

      - name: Install package (editable)
        run: pip install -e .

      - name: Test
        env:
          PYTHONPATH: src
        run: pytest -q
